export const ROUTE_PATHS = {
  login: '/login',
  register: '/register',
  dashboard: '/',
  studyPlanner: '/study-planner',
  learningResources: '/learning-resources',
  progressAnalytics: '/progress-analytics',
  readinessCheck: '/readiness-check',
  reminders: '/reminders',
  schedule: '/schedule',
  scheduleCreate: '/schedule/create',
  resources: '/resources',
  resourceById: '/resources/:id',
  progress: '/progress',
  tests: '/tests',
  takeTest: '/tests/:id/take',
  testResults: '/tests/:id/results',
  analysis: '/analysis',
  readiness: '/readiness',
  notes: '/notes',
  noteById: '/notes/:id',
  analytics: '/analytics',
  gamification: '/gamification',
  notifications: '/notifications',
  interview: '/interview',
  interviewSection: '/interview/:section',
  interviewDefault: '/interview/dashboard',
};
